### ISSUE TITLE
wrong code caption

### ISSUE THREAD

**Issue by jpkop** [tmuras/moodle-book#1]
Hi Tomasz,
I am working through the tutorial of your book. And I noticed that there are some copy pasted descriptions in your code snippets which are incorrect.
 I noticed it on pages 15 (2x Hello module), 17, 18 and 19 (2x) (First module: version.php).

Also the link to the chapter 4 code of this github poject on page 20 is broken. I assume it is because of the line break.
Best wishes
Jan

**Comment by tmuras** [comment]
Fixed, thank you!
Could you drop me your email to nexor1984 at gmail?
